Update Tutorial 1 - Training and Evaluation of Logistic Regression on Encrypted Data.ipynb
Fixed axis attribute error in data.drop() from 'columns' to axis=1
TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given